[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cheatmark"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic"
]

[tool.hatch.build.targets.wheel]
packages = ["src/cheatmark"]
